### ISSUE TITLE
Report: Investigations per origin by year: missing 2015

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#122]
When selecting years for the report: Investigations per origin by year, there is no selection box for year 2015.
![reportinvmissing2015](https://cloud.githubusercontent.com/assets/5039052/5976889/ab719e0a-a860-11e4-8acd-07b5030f1eb1.GIF)
The above also applies to the other reports where years are selected:
Investigations per status by year
Investigations per watershed by year
Investigations per problem type by year

Similarly for report: Investigations per status by month, there is a dropdown to select year and does not include 2015.  However you may enter 2015 but it doesn't appear in the list.

**Comment by gjmkelly** [comment]
I'm not familiar with the Activity Manager part of this.  So, same story ... we need to ask Lu or Jesse, or I need to know where this code is and spend time learning about it.

**Comment by gjmkelly** [comment]
And when it gets fixed, "selected years" needs to have logic so it displays up to the current year (meaning that just adding 2015 isn't a solution since you'd be wondering where 2016 was next year)  I also think a multi-select dropdown might work better than trying to display more and more checkboxes.

**Comment by jday3** [comment]
done

**Comment by rssidlowski** [comment]
I still see the same thing with the year check boxes and only up to 2014. Same as first screen shot in this issue.

**Comment by rssidlowski** [comment]
Using the corrected url: http://dpwdev.baltimorecity.gov/water/activitymanager/index.aspx works ok.  Would still like to see the years as selectable instead of check boxes hat would have to be updated every year.  Can you update to have the years in reverse chronological order so the most recent is first?

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Verified.
